import { DATA_LANDLIZ_DROP_1 } from "./data_Landliz Drop1";
import { DATA_LANDLIZ_DROP_10 } from "./data_Landliz Drop10";
import { DATA_LANDLIZ_DROP_11 } from "./data_Landliz Drop11";
import { DATA_LANDLIZ_DROP_12 } from "./data_Landliz Drop12";
import { DATA_LANDLIZ_DROP_13 } from "./data_Landliz Drop13";
import { DATA_LANDLIZ_DROP_14 } from "./data_Landliz Drop14";
import { DATA_LANDLIZ_DROP_15 } from "./data_Landliz Drop15";
import { DATA_LANDLIZ_DROP_16 } from "./data_Landliz Drop16";
import { DATA_LANDLIZ_DROP_17 } from "./data_Landliz Drop17";
import { DATA_LANDLIZ_DROP_18 } from "./data_Landliz Drop18";
import { DATA_LANDLIZ_DROP_19 } from "./data_Landliz Drop19";
import { DATA_LANDLIZ_DROP_2 } from "./data_Landliz Drop2";
import { DATA_LANDLIZ_DROP_20 } from "./data_Landliz Drop20";
import { DATA_LANDLIZ_DROP_21 } from "./data_Landliz Drop21";
import { DATA_LANDLIZ_DROP_22 } from "./data_Landliz Drop22";
import { DATA_LANDLIZ_DROP_23 } from "./data_Landliz Drop23";
import { DATA_LANDLIZ_DROP_24 } from "./data_Landliz Drop24";
import { DATA_LANDLIZ_DROP_25 } from "./data_Landliz Drop25";
import { DATA_LANDLIZ_DROP_26 } from "./data_Landliz Drop26";
import { DATA_LANDLIZ_DROP_27 } from "./data_Landliz Drop27";
import { DATA_LANDLIZ_DROP_28 } from "./data_Landliz Drop28";
import { DATA_LANDLIZ_DROP_29 } from "./data_Landliz Drop29";
import { DATA_LANDLIZ_DROP_3 } from "./data_Landliz Drop3";
import { DATA_LANDLIZ_DROP_30 } from "./data_Landliz Drop30";
import { DATA_LANDLIZ_DROP_31 } from "./data_Landliz Drop31";
import { DATA_LANDLIZ_DROP_32 } from "./data_Landliz Drop32";
import { DATA_LANDLIZ_DROP_33 } from "./data_Landliz Drop33";
import { DATA_LANDLIZ_DROP_34 } from "./data_Landliz Drop34";
import { DATA_LANDLIZ_DROP_35 } from "./data_Landliz Drop35";
import { DATA_LANDLIZ_DROP_36 } from "./data_Landliz Drop36";
import { DATA_LANDLIZ_DROP_37 } from "./data_Landliz Drop37";
import { DATA_LANDLIZ_DROP_38 } from "./data_Landliz Drop38";
import { DATA_LANDLIZ_DROP_39 } from "./data_Landliz Drop39";
import { DATA_LANDLIZ_DROP_4 } from "./data_Landliz Drop4";
import { DATA_LANDLIZ_DROP_40 } from "./data_Landliz Drop40";
import { DATA_LANDLIZ_DROP_41 } from "./data_Landliz Drop41";
import { DATA_LANDLIZ_DROP_42 } from "./data_Landliz Drop42";
import { DATA_LANDLIZ_DROP_43 } from "./data_Landliz Drop43";
import { DATA_LANDLIZ_DROP_44 } from "./data_Landliz Drop44";
import { DATA_LANDLIZ_DROP_45 } from "./data_Landliz Drop45";
import { DATA_LANDLIZ_DROP_46 } from "./data_Landliz Drop46";
import { DATA_LANDLIZ_DROP_47 } from "./data_Landliz Drop47";
import { DATA_LANDLIZ_DROP_48 } from "./data_Landliz Drop48";
import { DATA_LANDLIZ_DROP_49 } from "./data_Landliz Drop49";
import { DATA_LANDLIZ_DROP_5 } from "./data_Landliz Drop5";
import { DATA_LANDLIZ_DROP_50 } from "./data_Landliz Drop50";
import { DATA_LANDLIZ_DROP_51 } from "./data_Landliz Drop51";
import { DATA_LANDLIZ_DROP_52 } from "./data_Landliz Drop52";
import { DATA_LANDLIZ_DROP_53 } from "./data_Landliz Drop53";
import { DATA_LANDLIZ_DROP_54 } from "./data_Landliz Drop54";
import { DATA_LANDLIZ_DROP_55 } from "./data_Landliz Drop55";
import { DATA_LANDLIZ_DROP_56 } from "./data_Landliz Drop56";
import { DATA_LANDLIZ_DROP_57 } from "./data_Landliz Drop57";
import { DATA_LANDLIZ_DROP_58 } from "./data_Landliz Drop58";
import { DATA_LANDLIZ_DROP_59 } from "./data_Landliz Drop59";
import { DATA_LANDLIZ_DROP_6 } from "./data_Landliz Drop6";
import { DATA_LANDLIZ_DROP_60 } from "./data_Landliz Drop60";
import { DATA_LANDLIZ_DROP_61 } from "./data_Landliz Drop61";
import { DATA_LANDLIZ_DROP_62 } from "./data_Landliz Drop62";
import { DATA_LANDLIZ_DROP_63 } from "./data_Landliz Drop63";
import { DATA_LANDLIZ_DROP_64 } from "./data_Landliz Drop64";
import { DATA_LANDLIZ_DROP_65 } from "./data_Landliz Drop65";
import { DATA_LANDLIZ_DROP_66 } from "./data_Landliz Drop66";
import { DATA_LANDLIZ_DROP_67 } from "./data_Landliz Drop67";
import { DATA_LANDLIZ_DROP_68 } from "./data_Landliz Drop68";
import { DATA_LANDLIZ_DROP_69 } from "./data_Landliz Drop69";
import { DATA_LANDLIZ_DROP_7 } from "./data_Landliz Drop7";
import { DATA_LANDLIZ_DROP_70 } from "./data_Landliz Drop70";
import { DATA_LANDLIZ_DROP_71 } from "./data_Landliz Drop71";
import { DATA_LANDLIZ_DROP_72 } from "./data_Landliz Drop72";
import { DATA_LANDLIZ_DROP_73 } from "./data_Landliz Drop73";
import { DATA_LANDLIZ_DROP_74 } from "./data_Landliz Drop74";
import { DATA_LANDLIZ_DROP_75 } from "./data_Landliz Drop75";
import { DATA_LANDLIZ_DROP_76 } from "./data_Landliz Drop76";
import { DATA_LANDLIZ_DROP_77 } from "./data_Landliz Drop77";
import { DATA_LANDLIZ_DROP_8 } from "./data_Landliz Drop8";
import { DATA_LANDLIZ_DROP_9 } from "./data_Landliz Drop9";

const data = [];

data.push(DATA_LANDLIZ_DROP_1);
data.push(DATA_LANDLIZ_DROP_2);
data.push(DATA_LANDLIZ_DROP_3);
data.push(DATA_LANDLIZ_DROP_4);
data.push(DATA_LANDLIZ_DROP_5);
data.push(DATA_LANDLIZ_DROP_6);
data.push(DATA_LANDLIZ_DROP_7);
data.push(DATA_LANDLIZ_DROP_8);
data.push(DATA_LANDLIZ_DROP_9);
data.push(DATA_LANDLIZ_DROP_10);
data.push(DATA_LANDLIZ_DROP_11);
data.push(DATA_LANDLIZ_DROP_12);
data.push(DATA_LANDLIZ_DROP_13);
data.push(DATA_LANDLIZ_DROP_14);
data.push(DATA_LANDLIZ_DROP_15);
data.push(DATA_LANDLIZ_DROP_16);
data.push(DATA_LANDLIZ_DROP_17);
data.push(DATA_LANDLIZ_DROP_18);
data.push(DATA_LANDLIZ_DROP_19);
data.push(DATA_LANDLIZ_DROP_20);
data.push(DATA_LANDLIZ_DROP_21);
data.push(DATA_LANDLIZ_DROP_22);
data.push(DATA_LANDLIZ_DROP_23);
data.push(DATA_LANDLIZ_DROP_24);
data.push(DATA_LANDLIZ_DROP_25);
data.push(DATA_LANDLIZ_DROP_26);
data.push(DATA_LANDLIZ_DROP_27);
data.push(DATA_LANDLIZ_DROP_28);
data.push(DATA_LANDLIZ_DROP_29);
data.push(DATA_LANDLIZ_DROP_30);
data.push(DATA_LANDLIZ_DROP_31);
data.push(DATA_LANDLIZ_DROP_32);
data.push(DATA_LANDLIZ_DROP_33);
data.push(DATA_LANDLIZ_DROP_34);
data.push(DATA_LANDLIZ_DROP_35);
data.push(DATA_LANDLIZ_DROP_36);
data.push(DATA_LANDLIZ_DROP_37);
data.push(DATA_LANDLIZ_DROP_38);
data.push(DATA_LANDLIZ_DROP_39);
data.push(DATA_LANDLIZ_DROP_40);
data.push(DATA_LANDLIZ_DROP_41);
data.push(DATA_LANDLIZ_DROP_42);
data.push(DATA_LANDLIZ_DROP_43);
data.push(DATA_LANDLIZ_DROP_44);
data.push(DATA_LANDLIZ_DROP_45);
data.push(DATA_LANDLIZ_DROP_46);
data.push(DATA_LANDLIZ_DROP_47);
data.push(DATA_LANDLIZ_DROP_48);
data.push(DATA_LANDLIZ_DROP_49);
data.push(DATA_LANDLIZ_DROP_50);
data.push(DATA_LANDLIZ_DROP_51);
data.push(DATA_LANDLIZ_DROP_52);
data.push(DATA_LANDLIZ_DROP_52);
data.push(DATA_LANDLIZ_DROP_53);
data.push(DATA_LANDLIZ_DROP_54);
data.push(DATA_LANDLIZ_DROP_55);
data.push(DATA_LANDLIZ_DROP_56);
data.push(DATA_LANDLIZ_DROP_57);
data.push(DATA_LANDLIZ_DROP_58);
data.push(DATA_LANDLIZ_DROP_59);
data.push(DATA_LANDLIZ_DROP_60);
data.push(DATA_LANDLIZ_DROP_61);
data.push(DATA_LANDLIZ_DROP_62);
data.push(DATA_LANDLIZ_DROP_63);
data.push(DATA_LANDLIZ_DROP_64);
data.push(DATA_LANDLIZ_DROP_65);
data.push(DATA_LANDLIZ_DROP_66);
data.push(DATA_LANDLIZ_DROP_67);
data.push(DATA_LANDLIZ_DROP_68);
data.push(DATA_LANDLIZ_DROP_69);
data.push(DATA_LANDLIZ_DROP_70);
data.push(DATA_LANDLIZ_DROP_71);
data.push(DATA_LANDLIZ_DROP_72);
data.push(DATA_LANDLIZ_DROP_73);
data.push(DATA_LANDLIZ_DROP_74);
data.push(DATA_LANDLIZ_DROP_75);
data.push(DATA_LANDLIZ_DROP_76);
data.push(DATA_LANDLIZ_DROP_77);


export const DATA_LANDLIZ_DROP = data.flat(Infinity);